client_id: 3MVG9Y6d_Btp4xp4CbfgVpUoAB2fBp_Ob6jn.alYUgjV0QMBfJkEvye6B9x8vTxrEXh..NTUvdzBtNVFVKjvB
client_secret: 6431398207181831221
username: bruce@yue.com
password: meginfo86IX8RpywApDcyk6LZZNYbVpUv
host: login.salesforce.com
debugging: true