client_id: 3MVG9Y6d_Btp4xp4CbfgVpUoAB.AJ9UJYoDABdPVlPmwq8_82exgAzKJwXRaEH7rmtFCk6rhdm0jiWGypH.jN
client_secret: 9044592759507549551
username: bruce@yue.com
password: meginfo198786WDQezZlV13Fs8VCIInyHenI65
#host: login.salesforce.com
debugging: false